spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_project
    username: root
    password: system123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

#eureka server registry
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

